services:
  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    env_file:
      - ./.env
    ports:
      - "3307:3306"

  web:
    build:
      context: ./
      dockerfile: ./compose/Dockerfile
    container_name: django_backend
    command: python django_backend/manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.env
    environment:
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db/${MYSQL_DATABASE}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./:/app